#!/usr/bin/env python3
"""
Summarize Low-FF artificial sample performance patterns per original sample (preg_id).

Input: result_table_*.tsv generated by make_result.py
Output: a wide TSV table, one row per preg_id, showing (per ff_target):
  - pool outcome
  - donor outcome counts (TP/FN/HR_MISMATCH/NoCall)

Also provides convenience summary columns like:
  - min_ff_all_bg_tp: smallest ff_target where pool==TP and all donors==TP
  - min_ff_donor_all_tp: smallest ff_target where all donors==TP
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


OUTCOMES = ("TP", "FN", "HR_MISMATCH", "NoCall", "MISSING")


def ff_key(ff: float) -> str:
    # 3.5 -> ff3p5, 4.0 -> ff4
    s = f"{ff:.1f}"
    if s.endswith(".0"):
        s = s[:-2]
    s = s.replace(".", "p")
    return f"ff{s}"


def disease_class(orig_trisomy_list: str) -> str:
    s = "" if pd.isna(orig_trisomy_list) else str(orig_trisomy_list)
    if "Trisomy21" in s or "Trisomy18" in s or "Trisomy13" in s:
        return "Autosomal"
    # male manifest: mostly SCA-like tokens
    if any(t in s for t in ("XXY", "XYY", "XXX", "XO", "XXYY", "other")):
        return "SCA"
    return "Other"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--result-table", required=True, type=Path, help="Path to result_table_*.tsv")
    ap.add_argument("--out", required=True, type=Path, help="Output TSV path")
    ap.add_argument(
        "--ff-targets",
        default=None,
        help="Comma-separated ff targets to include (default: infer from table)",
    )
    args = ap.parse_args()

    df = pd.read_csv(args.result_table, sep="\t")
    required = {
        "preg_id",
        "ff_target",
        "bg_mode",
        "outcome",
        "bg_donors",
        "orig_trisomy_list",
        "orig_ff_yff",
        "orig_ff_seqff",
        "orig_json",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise SystemExit(f"Missing required columns in result table: {missing}")

    # Normalize
    df["ff_target"] = df["ff_target"].astype(float)
    df["outcome"] = df["outcome"].astype(str)

    if args.ff_targets:
        targets = [float(x.strip()) for x in args.ff_targets.split(",") if x.strip()]
    else:
        targets = sorted(df["ff_target"].unique().tolist())

    # One row per preg_id output
    rows = []
    for preg_id, g in df.groupby("preg_id", sort=True):
        g = g.copy()
        # stable "orig" info
        orig = g.iloc[0]
        row: dict[str, object] = {
            "preg_id": preg_id,
            "orig_json": orig["orig_json"],
            "orig_trisomy_list": orig["orig_trisomy_list"],
            "disease_class": disease_class(orig["orig_trisomy_list"]),
            "orig_ff_yff": orig["orig_ff_yff"],
            "orig_ff_seqff": orig["orig_ff_seqff"],
        }

        # Determine donor universe for this preg_id
        donor_rows = g[g["bg_mode"] == "donor"]
        donors = sorted({str(x) for x in donor_rows["bg_donors"].dropna().tolist()})
        row["donor_n"] = len(donors)

        min_ff_all_bg_tp = None
        min_ff_donor_all_tp = None

        for ff in targets:
            prefix = ff_key(ff)
            gf = g[g["ff_target"] == ff]

            # pool outcome (should be 1 row if present)
            pool = gf[gf["bg_mode"] == "pool"]
            if len(pool) == 0:
                pool_out = "MISSING"
            else:
                pool_out = str(pool.iloc[0]["outcome"])
            row[f"{prefix}_pool"] = pool_out

            # donor outcomes (counts)
            gd = gf[gf["bg_mode"] == "donor"]
            counts = gd["outcome"].value_counts().to_dict()
            donor_total = int(len(gd))
            row[f"{prefix}_donor_total"] = donor_total
            for o in OUTCOMES:
                if o == "MISSING":
                    continue
                row[f"{prefix}_donor_{o}"] = int(counts.get(o, 0))

            # Convenience: donor pass rate (TP fraction, exclude missing)
            if donor_total > 0:
                row[f"{prefix}_donor_tp_rate"] = round(int(counts.get("TP", 0)) / donor_total, 3)
            else:
                row[f"{prefix}_donor_tp_rate"] = ""

            # Determine thresholds
            donors_all_tp = (donor_total > 0) and (int(counts.get("TP", 0)) == donor_total)
            all_bg_tp = donors_all_tp and (pool_out == "TP")

            if donors_all_tp and (min_ff_donor_all_tp is None):
                min_ff_donor_all_tp = ff
            if all_bg_tp and (min_ff_all_bg_tp is None):
                min_ff_all_bg_tp = ff

        row["min_ff_donor_all_tp"] = "" if min_ff_donor_all_tp is None else min_ff_donor_all_tp
        row["min_ff_all_bg_tp"] = "" if min_ff_all_bg_tp is None else min_ff_all_bg_tp

        # Global summaries
        all_outcomes = g["outcome"].tolist()
        row["all_bg_all_tp"] = all(o == "TP" for o in all_outcomes)
        row["any_fail_ff_ge_4"] = bool(
            (g[g["ff_target"] >= 4.0]["outcome"].isin(["FN", "HR_MISMATCH", "NoCall"])).any()
        )
        row["any_fail_ff_ge_4p5"] = bool(
            (g[g["ff_target"] >= 4.5]["outcome"].isin(["FN", "HR_MISMATCH", "NoCall"])).any()
        )
        row["any_fail_at_5"] = bool(
            (g[g["ff_target"] == 5.0]["outcome"].isin(["FN", "HR_MISMATCH", "NoCall"])).any()
        )

        rows.append(row)

    out_df = pd.DataFrame(rows)

    # Friendly column order: basics first, then ff columns sorted
    base_cols = [
        "preg_id",
        "disease_class",
        "orig_trisomy_list",
        "orig_ff_yff",
        "orig_ff_seqff",
        "donor_n",
        "min_ff_donor_all_tp",
        "min_ff_all_bg_tp",
        "all_bg_all_tp",
        "any_fail_ff_ge_4",
        "any_fail_ff_ge_4p5",
        "any_fail_at_5",
        "orig_json",
    ]
    ff_cols = []
    for ff in targets:
        pfx = ff_key(ff)
        ff_cols.extend(
            [
                f"{pfx}_pool",
                f"{pfx}_donor_total",
                f"{pfx}_donor_TP",
                f"{pfx}_donor_FN",
                f"{pfx}_donor_HR_MISMATCH",
                f"{pfx}_donor_NoCall",
                f"{pfx}_donor_tp_rate",
            ]
        )
    cols = [c for c in base_cols if c in out_df.columns] + [c for c in ff_cols if c in out_df.columns]
    # include any leftover columns (shouldn't happen, but keep safe)
    cols += [c for c in out_df.columns if c not in cols]
    out_df = out_df[cols]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(args.out, sep="\t", index=False)
    print(f"[ok] wrote {args.out} rows={len(out_df)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

